### ISSUE TITLE
Publish new version to Chrome Web Store

### ISSUE THREAD

**Issue by floehopper** [freerange/freeagent_transaction_explainer#40]

**Comment by floehopper** [comment]
[New version published](https://chrome.google.com/webstore/detail/freeagent-transaction-exp/dcbkikjkmfjnjclhiphndgliaafiamhf?hl=en-US&gl=GB).

**Comment by floehopper** [comment]
I've tagged the repo with [v0.2](https://github.com/freerange/freeagent_transaction_explainer/releases/tag/v0.2) and taken a stab at guessing where [v0.1](https://github.com/freerange/freeagent_transaction_explainer/releases/tag/v0.1) should go.

**Comment by floehopper** [comment]
@chrisroos: I _think_ your Chrome app should automatically update to the new version at some point, but in all the messing about I haven't managed to verify that.

**Comment by chrisroos** [comment]
I've just checked and don't seem to have the FreeAgent Transaction Explainer installed at all at the moment (maybe something changed in my upgrade to Yosemite?) Irrespective I've now installed version 0.2.

I can still see [version 0.1 in the Chrome Web Store](https://chrome.google.com/webstore/detail/freeagent-transaction-exp/lgpgdkoopbcppnipcnbodcobjmhagmim). Maybe there's something we need to do to remove it? Shall I open a new issue for that?

**Comment by floehopper** [comment]
Hmm. Initially I tried to update the CWS developer dashboard "entry" for v0.1, but that didn't seem to be right. So then I added a new "entry" for v0.2. I couldn't find much useful info about upgrading, but I thought I read that Chrome should work out that a new version is present and automatically upgrade as long as the permissions it needs haven't changed. Maybe the simplest thing to do now is to un-publish v0.1. I'll do that now since it doesn't really serve any purpose.

**Comment by floehopper** [comment]
Hmm. Now I look at it again, maybe I'll have another go at *editing* the first entry.

**Comment by floehopper** [comment]
I've now managed to publish an *upgrade* to the [original extension](https://chrome.google.com/webstore/detail/freeagent-transaction-exp/lgpgdkoopbcppnipcnbodcobjmhagmim?hl=en-US&gl=GB). Note that the upgrade takes quite a while to be published (presumably some kind of CDN distribution issue).

Prior to doing this, I reinstalled v0.1 and then after v0.2 was published, I successfully upgraded by clicking the "Update extensions now" button at the top of the [extensions](chrome://extensions/) page in Chrome.

I've updated the link in the README in f2f63a6e49da1df9d5e348d0079ff323f5a3ce0b and also the link at the top of the GitHub repo page.

@chrisroos: I think it would be sensible if you uninstall the version you have installed and install the "new" one from [here](https://chrome.google.com/webstore/detail/freeagent-transaction-exp/lgpgdkoopbcppnipcnbodcobjmhagmim?hl=en-US&gl=GB).

**Comment by floehopper** [comment]
Unfortunately, I don't seem to be able to delete the extraneous "entry" in the CWS developer dashboard...

![2015-02-04 at 11 43](https://cloud.githubusercontent.com/assets/3169/6039857/32a1e8ca-ac63-11e4-9ee2-672a58253a9f.png)

**Comment by chrisroos** [comment]
I've just removed and re-installed the extension.

Thanks for sorting it all out, @jamesmead.

**Comment by floehopper** [comment]
:smile:
